name: CI de Java 

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-e-test:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout do código
        uses: actions/checkout@v4

      - name: 2. Configurar o Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: 3. Compilar o código
        
        run: javac ConversorTemperatura.java

      - name: 4. Executar os testes
   
        run: java ConversorTemperatura$ConversorTemperaturaTest